field: a96e85d9-ac1c-4a2b-a0d0-68f6bd2b2417 # Blog Content
fieldLayouts:
  1afe04ca-e313-4607-b104-dbd7487ccbea:
    tabs:
      -
        elements:
          -
            fieldUid: c5cb90d3-fe08-4f5f-8aa6-abf6603f2709 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  c5cb90d3-fe08-4f5f-8aa6-abf6603f2709: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'You may add in an image here.'
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:264e01a3-bd4b-44da-8657-c5dcf58c1c48' # Blog Images
      defaultUploadLocationSubpath: images/
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:264e01a3-bd4b-44da-8657-c5dcf58c1c48' # Blog Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: images
name: Images
sortOrder: 2
