columnSuffix: null
contentColumnType: string
fieldGroup: 22ce01ad-d01b-410b-98c5-c5cc7fe3b8e8 # Blog
handle: blogContent
instructions: ''
name: 'Blog Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_blogcontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
