defaultPlacement: end
enableVersioning: true
handle: blog
name: Blog
propagationMethod: all
siteSettings:
  ad8ea068-96be-4cc9-8890-6cec3a8cb753: # Irish Bitch
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry
    uriFormat: '{parent.uri}/{slug}'
type: channel
